datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://localhost:9090
    editable: true
    jsonData:
      timeInterval: 5s

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    editable: true
    jsonData:
      maxLines: 1000
      
  - name: Loki
    type: loki
    uid: loki
    url: http://localhost:3100
    editable: true
    jsonData:
      maxLines: 1000
      timeInterval: 5s

