receivers:
  filelog:
    include: [ /var/log/*.log ]
    start_at: beginning
    poll_interval: 500ms
    include_file_path: true
    include_file_name: true
    operators:
      - type: json_parser
        id: parse_json
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [loki, debug]

  telemetry:
    logs:
      level: "debug"
