receivers:
  filelog/json:
    include: [ /*/*.json ] # Ou qualquer padrão que pegue SÓ JSON
    # ... operadores específicos para JSON ...
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message

  filelog/text:
    include: [ /*/*.log ] # Ou qualquer padrão que pegue SÓ texto plano
    # ... operadores específicos para texto plano ...
    operators:
      - type: regex_parser
        regex: '^(?P<time>\S+)\s+\[?\s*(?i)(?P<level>[A-Z]+)\s*\]?\s+(?:(?P<application>[^:]+):\s*)?(?P<message>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [filelog/json, filelog/text]
      processors: [batch]
      exporters: [loki]

  telemetry:
    logs:
      level: "debug"
