auth_enabled: false  # Desabilita a autenticação (pode ser ajustado conforme necessário)

server:
  http_listen_port: 3100  # Porta HTTP para Loki
  grpc_listen_port: 9096  # Porta gRPC para Loki

ingester:
  wal:
    enabled: true
    dir: /loki/wal  # Diretório do Write-Ahead Log (WAL)
  chunk_target_size: 1048576  # Tamanho do chunk para os logs

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks  # Diretório onde os logs serão armazenados

schema_config:
  configs:
    - from: 2020-10-24  # Data de início para o armazenamento
      store: boltdb_shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h  # Período para retenção de índices

compactor:
  working_directory: /loki/compactor
  shared_storage: filesystem  # Tipo de armazenamento para compactação

limits_config:
  max_query_look_back: 0s  # Configuração de limite para consultas

chunk_target_size: 1048576
