receivers:
  filelog:
    include: [ /*/*/*.log ]
    start_at: beginning
    poll_interval: 500ms
    include_file_path: true
    include_file_name: true
    operators:
      - type: json_parser
        id: parse_json
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message

  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: 

exporters:
  otlphttp/metrics:
    endpoint: http://localhost:9090/api/v1/otlp
    tls:
      insecure: true
  otlphttp/traces:
    endpoint: http://localhost:4418
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://localhost:3100/otlp
    tls:
      insecure: true

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]

    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp/logs]

  telemetry:
    logs:
      level: "debug"
