receivers:
  filelog/json:
    include: [ /*/*.json ]
    include_file_path: false
    include_file_name: true
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message
      - type: add
        id: default_trace_fields
        attributes:
          trace_id: ""
          span_id: ""

  filelog/text:
    include: [ /*/*.log ]
    include_file_path: false
    include_file_name: true
    operators:
      - type: regex_parser
        regex: '^(?P<time>\S+)\s+\[?\s*(?i)(?P<level>[A-Z]+)\s*\]?\s+(?:(?P<application>[^:]+):\s*)?(?P<message>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%z'
        severity:
          parse_from: attributes.level
        body: attributes.message
      - type: add
        id: default_trace_fields
        attributes:
          trace_id: ""
          span_id: ""

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: 

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true  # Desative isso se usar HTTPS

  prometheus:
    endpoint: "localhost:8889"  # Prometheus faz scrape aqui  

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  debug:
    verbosity: detailed

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [filelog/json, filelog/text]
      processors: [batch]
      exporters: [loki, debug]

