services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel/config.yaml
      - logs:/log
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - loki
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    networks:
      - observability-network

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - observability-network

  monitoring-gateway:
    image: busybox
    command: >
      sh -c 'while true; do
        echo "{\"time\":\"$(date -u +%Y-%m-%dT%H:%M:%S%z)\", \"level\":\"info\",\"application\":\"monitoring-gateway\",\"message\":\"log de teste gerado automaticamente do monitoring-gateway\"}" >> /log/monitoring-gateway.json;
        sleep 5;
      done'
    volumes:
      - logs:/log
    networks:
      - observability-network
  monitoring-devices:
    image: busybox
    command: >
      sh -c 'while true; do
        echo "{\"time\":\"$(date -u +%Y-%m-%dT%H:%M:%S%z)\", \"level\":\"info\",\"application\":\"monitoring-devices\",\"message\":\"log de teste gerado automaticamente do monitoring-devices\"}" >> /log/monitoring-devices.json;
        sleep 5;
      done'
    volumes:
      - logs:/log
    networks:
      - observability-network

  monitoring-lote:
    image: busybox
    command: >
      sh -c 'while true; do
        echo "$(date -u +%Y-%m-%dT%H:%M:%S%z) [ INFO ]  log de teste gerado automaticamente do monitoring-lote" >> /log/monitoring-lote.log;
        sleep 5;
      done'
    volumes:
      - logs:/log
    networks:
      - observability-network

volumes:
  grafana-storage:
  logs:

networks:
  observability-network:
    driver: bridge
